[package]
name = "networkcopy-speed"
version = "2.3.0"
edition = "2024"

[features]
default = []
default-language-en = []

[dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }
blake3 = "1.8.5"
zstd = "0.13.3"
socket2 = "0.6.1"
eframe = { version = "0.35.0", default-features = false, features = [
    "default_fonts",
    "wgpu",
] }
rfd = "0.17.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "2.12.1", default-features = false, features = ["tls"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[build-dependencies]
winresource = "0.1.31"

[patch.crates-io]
winit = { path = "vendor/winit" }
