mod adaptive_compression;
mod calibrated_transfer;
mod compression_probe;
mod console_progress;
mod content_hash;
mod control_plane;
mod copy_bench;
mod destination_inventory;
mod direct_address;
mod direct_discovery;
mod direct_discovery_v4;
mod direct_link;
mod direct_route;
mod direct_tcp;
mod direct_transfer;
mod file_metadata;
pub mod gui_session;
pub mod gui_transfer;
mod iocp_copy;
mod iocp_file_probe;
mod iocp_probe;
mod manifest_scan;
mod multistream_copy;
mod network_calibration;
mod pipeline_bench;
mod resume_state;
mod striped_file;
mod tcp_connect;
mod tiny_pack_codec;
mod transfer_memory;
mod update_verification;
pub mod windows_elevation;
mod windows_file_replace;
mod windows_setup;
mod zstd_dictionary_bench;

include!("cli_main.rs");
