mod adaptive_compression;
mod calibrated_transfer;
mod cdc_basis_index;
mod cdc_lane;
mod cdc_reconstruction_bench;
mod compression_probe;
mod console_progress;
mod content_defined_dedup_bench;
mod content_hash;
mod control_plane;
mod copy_bench;
mod dedup_comparison_bench;
mod destination_inventory;
pub mod destination_layout;
mod direct_address;
mod direct_discovery;
mod direct_discovery_v4;
mod direct_link;
mod direct_route;
mod direct_tcp;
mod direct_transfer;
mod file_metadata;
mod fixed_block_dedup_bench;
mod folder_dedup_bench;
pub mod gui_session;
pub mod gui_transfer;
mod iocp_copy;
mod iocp_file_probe;
mod iocp_probe;
pub mod management_active_binding;
pub mod management_active_binding_codec;
pub mod management_agent;
pub mod management_control;
pub mod management_direct;
pub mod management_directory;
pub mod management_discovery;
mod management_filesystem;
pub mod management_instance;
pub mod management_jobs;
pub mod management_orchestration;
#[path = "management_persistence_v4.rs"]
pub mod management_persistence;
pub mod management_protocol;
pub mod management_queue;
pub mod management_reconnect;
pub mod management_route;
pub mod management_snapshot;
mod manifest_scan;
mod multistream_copy;
mod network_calibration;
mod pipeline_bench;
pub mod release_update;
mod resume_state;
pub mod session_cdc_catalog;
mod session_cdc_lane;
mod striped_file;
mod tcp_connect;
mod tiny_file_materialize;
mod tiny_file_pool;
mod tiny_file_write_bench;
mod tiny_pack_codec;
mod transfer_memory;
mod update_verification;
pub mod windows_agent_tray;
pub mod windows_elevation;
mod windows_file_replace;
mod windows_icon;
pub mod windows_notification;
mod windows_setup;
mod zstd_dictionary_bench;

include!("cli_main.rs");
